---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: my-azurefile
